# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CSGetAccountBriefInfoBeforeLoginRes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CSGetAccountBriefInfoBeforeLoginRes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)CSGetAccountBriefInfoBeforeLoginRes.proto\x12\x05proto\"\x94\x01\n#CSGetAccountBriefInfoBeforeLoginRes\x12\x12\n\naccount_id\x18\x01 \x01(\x04\x12\x10\n\x08nickname\x18\x02 \x01(\t\x12\x10\n\x08head_pic\x18\x03 \x01(\r\x12\x11\n\tbanner_id\x18\x04 \x01(\r\x12\r\n\x05level\x18\x05 \x01(\r\x12\x13\n\x0block_reigon\x18\x06 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CSGetAccountBriefInfoBeforeLoginRes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CSGETACCOUNTBRIEFINFOBEFORELOGINRES']._serialized_start=53
  _globals['_CSGETACCOUNTBRIEFINFOBEFORELOGINRES']._serialized_end=201
# @@protoc_insertion_point(module_scope)
