# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MajorLoginRes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'MajorLoginRes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13MajorLoginRes.proto\x12\x05proto\"Q\n\x10\x42lacklistInfoRes\x12\x12\n\nban_reason\x18\x01 \x01(\x05\x12\x17\n\x0f\x65xpire_duration\x18\x02 \x01(\r\x12\x10\n\x08\x62\x61n_time\x18\x03 \x01(\r\"f\n\x0eLoginQueueInfo\x12\r\n\x05\x61llow\x18\x01 \x01(\x08\x12\x16\n\x0equeue_position\x18\x02 \x01(\r\x12\x16\n\x0eneed_wait_secs\x18\x03 \x01(\r\x12\x15\n\rqueue_is_full\x18\x04 \x01(\x08\"x\n\x10\x46\x46\x41ntiConfigDesc\x12\x0e\n\x06region\x18\x01 \x01(\t\x12\x0e\n\x06\x65nable\x18\x02 \x01(\x08\x12\x12\n\nhpe_enable\x18\x03 \x01(\x08\x12\x12\n\nffi_enable\x18\x04 \x01(\x08\x12\x1c\n\x14mtp_lite_data_enable\x18\x05 \x01(\x08\"\x90\x04\n\rMajorLoginRes\x12\x12\n\naccount_id\x18\x01 \x01(\x04\x12\x13\n\x0block_region\x18\x02 \x01(\t\x12\x13\n\x0bnoti_region\x18\x03 \x01(\t\x12\x11\n\tip_region\x18\x04 \x01(\t\x12\x19\n\x11\x61gora_environment\x18\x05 \x01(\t\x12\x19\n\x11new_active_region\x18\x06 \x01(\t\x12\x19\n\x11recommend_regions\x18\x07 \x03(\t\x12\r\n\x05token\x18\x08 \x01(\t\x12\x0b\n\x03ttl\x18\t \x01(\r\x12\x12\n\nserver_url\x18\n \x01(\t\x12\x16\n\x0e\x65mulator_score\x18\x0b \x01(\r\x12*\n\tblacklist\x18\x0c \x01(\x0b\x32\x17.proto.BlacklistInfoRes\x12)\n\nqueue_info\x18\r \x01(\x0b\x32\x15.proto.LoginQueueInfo\x12\x0e\n\x06tp_url\x18\x0e \x01(\t\x12\x15\n\rapp_server_id\x18\x0f \x01(\r\x12\x0f\n\x07ip_city\x18\x10 \x01(\t\x12\x16\n\x0eip_subdivision\x18\x11 \x01(\t\x12\x0b\n\x03kts\x18\x12 \x01(\r\x12\n\n\x02\x61k\x18\x13 \x01(\x0c\x12\x0b\n\x03\x61iv\x18\x14 \x01(\x0c\x12\x12\n\nffanti_url\x18\x15 \x01(\t\x12\x34\n\x13\x66\x66_anti_config_desc\x18\x16 \x01(\x0b\x32\x17.proto.FFAntiConfigDesc*\x18\n\tBanReason\x12\x0b\n\x07UNKNOWN\x10\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MajorLoginRes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BANREASON']._serialized_start=870
  _globals['_BANREASON']._serialized_end=894
  _globals['_BLACKLISTINFORES']._serialized_start=30
  _globals['_BLACKLISTINFORES']._serialized_end=111
  _globals['_LOGINQUEUEINFO']._serialized_start=113
  _globals['_LOGINQUEUEINFO']._serialized_end=215
  _globals['_FFANTICONFIGDESC']._serialized_start=217
  _globals['_FFANTICONFIGDESC']._serialized_end=337
  _globals['_MAJORLOGINRES']._serialized_start=340
  _globals['_MAJORLOGINRES']._serialized_end=868
# @@protoc_insertion_point(module_scope)
